pool:
  #using ubuntu works just fine
  #vmImage: "ubuntu-16.04" 
  #using windows will show garbled text
  vmImage: "vs2017-win2016"

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "8.x"
    displayName: "Install Node.js"
  - script: yarn bootstrap
  - script: yarn test
